# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Habheat < Formula
  desc "A simple terminal UI for habit tracking with Github like heat map, written in Go"
  homepage "https://github.com/metagunner/habheat/"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/metagunner/habheat/releases/download/v0.1.1/habheat_Darwin_x86_64.tar.gz"
      sha256 "9c1a94ee77b504c07a79545f1a2166aa21507504680b5c188044720104f9b105"

      def install
        bin.install "habheat"
      end
    end
    on_arm do
      url "https://github.com/metagunner/habheat/releases/download/v0.1.1/habheat_Darwin_arm64.tar.gz"
      sha256 "6e63594ae1c29f64c8e325071544ea3caf2780e8fca5d6e7227372e9205cf0ef"

      def install
        bin.install "habheat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metagunner/habheat/releases/download/v0.1.1/habheat_Linux_x86_64.tar.gz"
        sha256 "21dc3031f8daaaedc28cb191a001c4e89ece7038f94e69029b4b57d81ae96cd7"

        def install
          bin.install "habheat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metagunner/habheat/releases/download/v0.1.1/habheat_Linux_arm64.tar.gz"
        sha256 "ddf5b8641e30f31cecdc95ddeb78568c6093709cdb0e89420e4a32f69331722b"

        def install
          bin.install "habheat"
        end
      end
    end
  end
end
